### ISSUE TITLE
error while importing bitbnspy

### ISSUE THREAD

**Issue by seshadri27** [bitbns-official/bitbnspy#22] opened 2021-02-28 15:50 UTC
hi I have installed bitbnspy from anaconda command prompt in windows10 using following:
pip3 install python-socketio
pip3 install bitbnspy

Installation was successful. When I am trying to import bitbnspy I am getting error:

```
(base) C:\Users\USER>python
Python 3.7.4 (default, Aug  9 2019, 18:34:13) [MSC v.1915 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from bitbnspy import bitbns
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'bitbnspy'

```
Could you please advice how to resolve this error?

**Comment by kprajaguru** [comment] 2021-05-22 15:17
did it got sorted, am also facing similar issue?

**Comment by kprajaguru** [comment] 2021-05-22 15:21
ok I have sorted this. 

Try the following snippet!


from bitbnspy import bitbns
apiKey = 'A2DF8532214EABDDD0CB92A15289ED39'
apiSecretKey = '090A80EB9F7C7B2100CCED9BC143DF0E'
bitbnsObj = bitbns(apiKey, apiSecretKey)
bitbnsObj.platformStatus()

**Comment by sanket-buyhatke** [comment] 2021-05-22 15:39
hi, @seshadri27 was able to check it in the environment you have specified, it seems to be working, 
could you pls try :
`pip freeze | findstr "bitbns requests"` ? and ping the response (would help finding the error)

if you are unable to find those packages, then mostly likely the installation was not completed properly, would suggest trying the installation again.

pls do ping, if the issue persists

**Comment by sanket-buyhatke** [comment] 2021-05-22 15:41
hi, @kprajaguru, thank you for the assist, but would suggest you revoke your API keys and create new ones, as they can be potentially be misused by bad actors endangering your capital, since they have been exposed.

**Comment by CO17349** [comment] 2021-05-27 11:47
Hi, how can i generate new API key for myself as the one mentioned by @kprajaguru doesn't seem to work. Thanks

**Comment by CO17349** [comment] 2021-05-28 05:57
@sanket-buyhatke, thank you very much.

**Comment by its-mohnish** [comment] 2021-06-07 08:47
@seshadri27 Hey, Did you get the issue sorted? I think the problem is that you have installed the libraries through pip3 and are now trying to run it in python. 

Just try running the commands mentioned below - 
`pip install bitbnspy`
`pip install python-socketio`

Then try running python and see if it works or not.

**Comment by sanket-buyhatke** [comment] 2021-08-02 10:06
hi @seshadri27, will be closing this issue, feel free to re-open if you face the issue again.

**Closed by sanket-buyhatke** 2021-08-02 10:06 UTC
Labels: question
